packages:
  - "*/"
  - "!_*/"
  - "!.*/"
  - "!build/"
  - "!node_modules/"

overrides:
  diff@^8.0.0: ^8.0.3
  tar@6: ^7.5.8
  'ajv@^8': '^8.18.0'
  'rollup@^4': '^4.59.0'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
