packages:
  - "*/"
  - "!_*/"
  - "!.*/"
  - "!build/"
  - "!node_modules/"

overrides:
  'ajv@^8': '^8.18.0'
  'picomatch@^4': '^4.0.4'
  'postcss@^8': '^8.5.10'
  'rollup@^4': '^4.59.0'
  'tar@^6': '^7.5.11'
  'uuid@^9': '^14.0.0'
  'ws@^8': '^8.20.1'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
