packages:
  - "*/"
  - "!_*/"
  - "!.*/"
  - "!build/"
  - "!node_modules/"

overrides:
  'ajv@^8': '^8.18.0'
  'rollup@^4': '^4.59.0'
  'tar@^6': '^7.5.11'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
ignoreWorkspaceCycles: true
